language: python
before_install:
  - sudo add-apt-repository -y ppa:presslabs/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq luajit luarocks
install:
  - sudo luarocks install busted
  - sudo sed -i 's#/usr/bin/lua#$LUA#g' /usr/local/bin/busted
  - wget https://gitorious.org/mdb/mdb/archive/aa3463ec7c5e979420b13c8f37caa377ed2c1cf1.tar.gz -O/tmp/lmdb.tar.gz
  - cd /tmp ; tar -zxf /tmp/lmdb.tar.gz ; cd /tmp/mdb-mdb/libraries/liblmdb ; make ; sudo make install ; sudo ln -sf /usr/local/lib/liblmdb.so /usr/lib/
script: cd $TRAVIS_BUILD_DIR/src ; luajit -e 'local l = require "lmdb" v = l.version() print(v)' ; cd $TRAVIS_BUILD_DIR ; LUA=luajit busted -o TAP
